server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin # If you plan to use an admin path, you'll need to also use non-root app path
  connector:
    type: http
    port: 8080
logging:
  level: INFO
  loggers:
    tokekbesi: DEBUG
